# Generated by Django 4.0.2 on 2022-03-19 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_business_details_id_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='irich_walletamount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.wallet'),
        ),
    ]
