# Generated by Django 4.0.2 on 2022-04-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_employee_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_user',
            field=models.BooleanField(default=False),
        ),
    ]
