# Generated by Django 4.0.2 on 2022-04-08 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_remove_employee_is_user_employee_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_active',
        ),
    ]
